language: java

script:
  - cd aula-01/java && mvn clean test 
  - cd aula-01/java && checkstyle:check
  - cd aula-01/java && spotbugs:check 

  - cd aula-07/java && mvn clean test
  - cd aula-07/java && checkstyle:check
  - cd aula-07/java && spotbugs:check 
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
jdk:
  - oraclejdk11
