language: java

script:
  - cd aula-01/java && mvn test checkstyle:check spotbugs:check 
  - cd ../..
  - cd aula-07/vetor/java && mvn test checkstyle:check spotbugs:check 
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
jdk:
  - oraclejdk11
